import MenuItem from "../types/menu";

const fakeMenuData : MenuItem[] = [
    {
        id: 1,
        name: '权限管理',
        label: '权限管理',
        parentId: -1,
        path: '/admin',
        permission: null,
        sort: 0,
        icon: 'el-icon-s-operation',
        children: [
          {
            id: 11,
            name: '用户管理',
            label: '用户管理',
            parentId: 1,
            path: '/admin/user',
            permission: null,
            sort: 0,
            icon: 'el-icon-s-operation',
            children: [], // 子菜单为空
          },
        ],
      },
    {
        id: 2,
        name: '设置管理',
        label: '设置管理',
        parentId: -1,
        path: '/settings',
        permission: null,
        sort: 1,
        icon: 'el-icon-setting',
        children: [],
      },
      {
        id: 10127,
        name: '根因分析',
        label: '根因分析',
        parentId: -1,
        path: '/causeAnalysis',
        permission: null,
        sort: 905,
        icon: 'icon-mobile',
        children: [],
      },  
      {
        id: 10128,
        name: '根因分析',
        label: '根因分析',
        parentId: -1,
        path: '/causeAnalysis',
        permission: null,
        sort: 905,
        icon: 'icon-mobile',
        children: [],
      }, 
      {
        id: 10129,
        name: '应急事件信息展示',
        label: '应急事件信息展示',
        parentId: -1,
        path: '/emergencyShow',
        permission: null,
        sort: 906,
        icon: 'icon-mobile',
        children: [],
      },
      {
        id: 10130,
        name: '应急事件信息编辑',
        label: '应急事件信息编辑',
        parentId: -1,
        path: '/emergencyEdit',
        permission: null,
        sort: 906,
        icon: 'icon-mobile',
        children: [],
      },
      {
        id: 10131,
        name: '营销中心',
        label: '营销中心',
        parentId: -1,
        path: '/emergencyEdit',
        permission: null,
        sort: 906,
        icon: 'icon-mobile',
        children: [],
      },
      {
        id: 10132,
        name: '实体渠道',
        label: '实体渠道',
        parentId: -1,
        path: '/emergencyEdit',
        permission: null,
        sort: 906,
        icon: 'icon-mobile',
        children: [],
      },
      {
        id: 10133,
        name: '开放平台',
        label: '开放平台',
        parentId: -1,
        path: '/emergencyEdit',
        permission: null,
        sort: 906,
        icon: 'icon-mobile',
        children: [],
      },
      {
        id: 10134,
        name: 'USAP',
        label: 'USAP',
        parentId: -1,
        path: '/emergencyEdit',
        permission: null,
        sort: 906,
        icon: 'icon-mobile',
        children: [],
      },
      {
        id: 10135,
        name: '短信服务',
        label: 'SMS',
        parentId: -1,
        path: '/emergencyEdit',
        permission: null,
        sort: 906,
        icon: 'icon-mobile',
        children: [],
      },
      {
        id: 10135,
        name: 'IT服务管理端',
        label: 'IT服务管理端',
        parentId: -1,
        path: '/management',
        permission: null,
        sort: 906,
        icon: 'icon-mobile',
        children: [
            {
                id: 10136,
                name: '重保日历',
                label: '重保日历',
                parentId: -1,
                path: '/management/calendar',
                permission: null,
                sort: 906,
                icon: 'icon-mobile',
                children: [],
              },
              {
                id: 10137,
                name: '带宽容量',
                label: '带宽容量',
                parentId: -1,
                path: '/emergencyEdit',
                permission: null,
                sort: 906,
                icon: 'icon-mobile',
                children: [],
              },
              {
                id: 10137,
                name: 'IT资产',
                label: '带宽容量',
                parentId: -1,
                path: '/emergencyEdit',
                permission: null,
                sort: 906,
                icon: 'icon-mobile',
                children: [],
              },
        ],
      },
      
]

export default fakeMenuData;